name: build-resources

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64]
        node-version: [lts/*, latest]
    name: build on ${{ matrix.os }} ${{ matrix.architecture }} node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          check-latest: true
      - run: |
          cd build
          npm i --ignore-scripts
          npm run build
